create table ot_trans
(
  trans_seqno          VARCHAR(50) not null,
  trans_date           DATE,
  trans_datetime       datetime,
  trans_merseqno       VARCHAR(50),
  trans_merdate        DATE,
  trans_merdatetime    datetime,
  trans_hostseqno      VARCHAR(50),
  trans_hostdate       DATE,
  trans_hostdatetime   datetime,
  trans_orgmerseqno    VARCHAR(50),
  trans_orgmerdate     DATE,
  trans_orgseqno       VARCHAR(50),
  trans_orgdate        DATE,
  trans_orgdatetime    datetime,
  trans_orghostseqno   VARCHAR(50),
  trans_orghostdate    DATE,
  trans_id             VARCHAR(4),
  mer_id               VARCHAR(50),
  sub_mer_id           VARCHAR(50),
  trans_amt            DECIMAL(20,2),
  trans_currency       VARCHAR(3),
  trans_amt1           DECIMAL(20,2),
  trans_amt2           DECIMAL(20,2),
  trans_amt3           DECIMAL(20,2),
  trans_amt4           DECIMAL(20,2),
  trans_feeamt         DECIMAL(20,2),
  trans_returncode     VARCHAR(30),
  trans_returnMsg      VARCHAR(300),
  trans_status         VARCHAR(2),
  trans_step           VARCHAR(2),
  trans_procstatus     VARCHAR(1),
  trans_remark1        VARCHAR(2),
  trans_remark2        VARCHAR(2),
  trans_type           VARCHAR(20),
  appid                VARCHAR(50),
  openid               VARCHAR(200),
  banktype             VARCHAR(50),
  agent_id             VARCHAR(20),
  bank_id              VARCHAR(20),
  trans_cleardate      DATE,
  trans_departmentid   VARCHAR(10),
  pay_type             VARCHAR(20),
  cashier_id           VARCHAR(100),
  PRIMARY KEY (trans_seqno)
);

create table ht_trans
(
  trans_seqno          VARCHAR(50) not null,
  trans_date           DATE,
  trans_datetime       datetime,
  trans_merseqno       VARCHAR(50),
  trans_merdate        DATE,
  trans_merdatetime    datetime,
  trans_hostseqno      VARCHAR(50),
  trans_hostdate       DATE,
  trans_hostdatetime   datetime,
  trans_orgmerseqno    VARCHAR(50),
  trans_orgmerdate     DATE,
  trans_orgseqno       VARCHAR(50),
  trans_orgdate        DATE,
  trans_orgdatetime    datetime,
  trans_orghostseqno   VARCHAR(50),
  trans_orghostdate    DATE,
  trans_id             VARCHAR(4),
  mer_id               VARCHAR(50),
  sub_mer_id           VARCHAR(50),
  trans_amt            DECIMAL(20,2),
  trans_currency       VARCHAR(3),
  trans_amt1           DECIMAL(20,2),
  trans_amt2           DECIMAL(20,2),
  trans_amt3           DECIMAL(20,2),
  trans_amt4           DECIMAL(20,2),
  trans_feeamt         DECIMAL(20,2),
  trans_returncode     VARCHAR(30),
  trans_returnMsg      VARCHAR(300),
  trans_status         VARCHAR(2),
  trans_step           VARCHAR(2),
  trans_procstatus     VARCHAR(1),
  trans_remark1        VARCHAR(2),
  trans_remark2        VARCHAR(2),
  trans_type           VARCHAR(20),
  appid                VARCHAR(50),
  openid               VARCHAR(200),
  banktype             VARCHAR(50),
  agent_id             VARCHAR(20),
  bank_id              VARCHAR(20),
  trans_cleardate      DATE,
  trans_departmentid   VARCHAR(10),
  pay_type             VARCHAR(20),
  cashier_id           VARCHAR(100),
  PRIMARY KEY (trans_seqno)
);

create table ht_trans_all
(
  trans_seqno          VARCHAR(50) not null,
  trans_date           DATE,
  trans_datetime       datetime,
  trans_merseqno       VARCHAR(50),
  trans_merdate        DATE,
  trans_merdatetime    datetime,
  trans_hostseqno      VARCHAR(50),
  trans_hostdate       DATE,
  trans_hostdatetime   datetime,
  trans_orgmerseqno    VARCHAR(50),
  trans_orgmerdate     DATE,
  trans_orgseqno       VARCHAR(50),
  trans_orgdate        DATE,
  trans_orgdatetime    datetime,
  trans_orghostseqno   VARCHAR(50),
  trans_orghostdate    DATE,
  trans_id             VARCHAR(4),
  mer_id               VARCHAR(50),
  sub_mer_id           VARCHAR(50),
  trans_amt            DECIMAL(20,2),
  trans_currency       VARCHAR(3),
  trans_amt1           DECIMAL(20,2),
  trans_amt2           DECIMAL(20,2),
  trans_amt3           DECIMAL(20,2),
  trans_amt4           DECIMAL(20,2),
  trans_feeamt         DECIMAL(20,2),
  trans_returncode     VARCHAR(30),
  trans_returnMsg      VARCHAR(300),
  trans_status         VARCHAR(2),
  trans_step           VARCHAR(2),
  trans_procstatus     VARCHAR(1),
  trans_remark1        VARCHAR(2),
  trans_remark2        VARCHAR(2),
  trans_type           VARCHAR(20),
  appid                VARCHAR(50),
  openid               VARCHAR(200),
  banktype             VARCHAR(50),
  agent_id             VARCHAR(20),
  bank_id              VARCHAR(20),
  trans_cleardate      DATE,
  trans_departmentid   VARCHAR(10),
  pay_type             VARCHAR(20),
  cashier_id           VARCHAR(100),
  PRIMARY KEY (trans_seqno)
);

create table bt_clear_trans
(
  trans_seqno          VARCHAR(50) not null,
  trans_date           DATE,
  trans_datetime       datetime,
  trans_merseqno       VARCHAR(50),
  trans_merdate        DATE,
  trans_merdatetime    datetime,
  trans_hostseqno      VARCHAR(50),
  trans_hostdate       DATE,
  trans_hostdatetime   datetime,
  trans_orgmerseqno    VARCHAR(50),
  trans_orgmerdate     DATE,
  trans_orgseqno       VARCHAR(50),
  trans_orgdate        DATE,
  trans_orgdatetime    datetime,
  trans_orghostseqno   VARCHAR(50),
  trans_orghostdate    DATE,
  trans_id             VARCHAR(4),
  mer_id               VARCHAR(50),
  sub_mer_id           VARCHAR(50),
  trans_amt            DECIMAL(20,2),
  trans_currency       VARCHAR(3),
  trans_amt1           DECIMAL(20,2),
  trans_amt2           DECIMAL(20,2),
  trans_amt3           DECIMAL(20,2),
  trans_amt4           DECIMAL(20,2),
  trans_feeamt         DECIMAL(20,2),
  trans_returncode     VARCHAR(30),
  trans_returnMsg      VARCHAR(300),
  trans_status         VARCHAR(2),
  trans_step           VARCHAR(2),
  trans_procstatus     VARCHAR(1),
  trans_remark1        VARCHAR(2),
  trans_remark2        VARCHAR(2),
  trans_type           VARCHAR(20),
  appid                VARCHAR(50),
  openid               VARCHAR(200),
  banktype             VARCHAR(50),
  agent_id             VARCHAR(20),
  bank_id              VARCHAR(20),
  trans_cleardate      DATE,
  trans_departmentid   VARCHAR(10),
  pay_type             VARCHAR(20),
  cashier_id           VARCHAR(100),
  PRIMARY KEY (trans_seqno)
);


create table ft_batch_ctrl(
  bp_departmentid   VARCHAR(30),
  bp_cleardate      DATE,
  bp_procdate       datetime,
  bp_enddate        datetime,
  bp_phase          VARCHAR(1),
  bp_status         VARCHAR(1),
  PRIMARY KEY (bp_departmentid)
);

create table ft_department(
  departmentid      VARCHAR(30),
  bankid            VARCHAR(30),
  parentid          VARCHAR(30),
  departmentcode    VARCHAR(30),
  departmentname    VARCHAR(60),
  departmenttype    VARCHAR(1),
  departmentdate    DATE,
  province          VARCHAR(10),
  city              VARCHAR(10),
  address           VARCHAR(60),
  zipcode           VARCHAR(6),
  phone             VARCHAR(20),
  email             VARCHAR(32),
  status            VARCHAR(1),
  PRIMARY KEY (departmentid)
);

create table ft_bussetting(
  bus_departmentid       VARCHAR(30),
  bus_precleardate       DATE,
  bus_cleardate          DATE,
  bus_cutoffprocdate     DATE,
  bus_cutoffprocstatus   VARCHAR(1),
  bus_businessno         VARCHAR(15),
  bus_headofficeacctno   VARCHAR(30),
  bus_profitperiod       VARCHAR(1),
  bus_merresptimes       DECIMAL(6),
  bus_merrespinterval    DECIMAL(6),
  bus_withdrawmonths     DECIMAL(6),
  bus_systemstatus       VARCHAR(1),
  primary key (bus_departmentid)
 );
 
 create table bt_host_trans(
  trans_hostseqno varchar(50), 
  trans_seqno varchar(50), 
  trans_businessno varchar(15), 
  trans_date DATE, 
  trans_hostdate DATE, 
  trans_busdeptid varchar(4), 
  trans_acctdeptid varchar(4), 
  trans_id varchar(4), 
  trans_tellerid varchar(6), 
  trans_payacctno varchar(22), 
  trans_rcvacctno varchar(22), 
  trans_amt decimal(15,2), 
  trans_currency varchar(3), 
  trans_dcflag varchar(1), 
  trans_status varchar(1), 
  trans_checkstatus varchar(1), 
  trans_departmentid varchar(30),
  primary key (trans_hostseqno,trans_id)
  );
  
  create table ht_host_trans(
  trans_hostseqno varchar(50), 
  trans_seqno varchar(50), 
  trans_businessno varchar(15), 
  trans_date DATE, 
  trans_hostdate DATE, 
  trans_busdeptid varchar(4), 
  trans_acctdeptid varchar(4), 
  trans_id varchar(4), 
  trans_tellerid varchar(6), 
  trans_payacctno varchar(22), 
  trans_rcvacctno varchar(22), 
  trans_amt decimal(15,2), 
  trans_currency varchar(3), 
  trans_dcflag varchar(1), 
  trans_status varchar(1), 
  trans_checkstatus varchar(1), 
  trans_departmentid varchar(30),
  primary key (trans_hostseqno,trans_id)
  );
  
  create table bt_mer_trans(
  trans_seqno          VARCHAR(50) not null,
  trans_date           DATE,
  trans_datetime       datetime,
  mer_id               VARCHAR(50),
  sub_mer_id           VARCHAR(50),
  trans_amt            DECIMAL(20,2),
  trans_feeamt         DECIMAL(20,2),
  trans_type           VARCHAR(20),
  trans_cleardate      DATE,
  trans_departmentid   VARCHAR(10),
  trans_settstatus      VARCHAR(1),
  pay_type             VARCHAR(20),
  PRIMARY KEY (trans_seqno)
  );
  
  create table bt_mer_sett(
  trans_settdate       DATE,
  trans_settdatetime   datetime,
  trans_cleardate      DATE not null,
  mer_id               VARCHAR(50),
  sub_mer_id           VARCHAR(50) not null,
  pay_type             VARCHAR(20) not null,
  sett_totalcount      VARCHAR(20),
  sett_totalamt        DECIMAL(20,2),
  sett_totalfeeamt     DECIMAL(20,2),
  trans_departmentid   VARCHAR(10) ,
  PRIMARY KEY (trans_cleardate,sub_mer_id,pay_type)
  );
  
  create table ht_mer_trans(
  trans_seqno          VARCHAR(50) not null,
  trans_date           DATE,
  trans_datetime       datetime,
  mer_id               VARCHAR(50),
  sub_mer_id           VARCHAR(50),
  trans_amt            DECIMAL(20,2),
  trans_feeamt         DECIMAL(20,2),
  trans_type           VARCHAR(20),
  trans_cleardate      DATE,
  trans_departmentid   VARCHAR(10),
  trans_settstatus     VARCHAR(1),
  pay_type             VARCHAR(20),
  PRIMARY KEY (trans_seqno)
  );
  
  create table ot_query(
  trans_seqno      VARCHAR(50) not null,
  trans_date       DATE,
  trans_sendtimes  INT,
  PRIMARY KEY (trans_seqno)
  );
  
  create table ft_pay_passageway(
  passageway_name   VARCHAR(100),
  pay_type          VARCHAR(20) not null,
  pay_departmentid  VARCHAR(10),
  mer_id            VARCHAR(50),
  rate              DECIMAL(10,4),
  open_date         DATE,
  modify_date       DATE,
  PRIMARY KEY (pay_type,pay_departmentid)
  );
  
  create table bt_check_error(
  trans_hostseqno      VARCHAR(50) not null,
  trans_hostdate       DATE,
  trans_seqno          VARCHAR(50),
  trans_date           DATE,
  Trans_BusinessNo     VARCHAR(50),
  Trans_BusDeptId      VARCHAR(50),
  Trans_AcctDeptId     VARCHAR(50),
  Trans_Id             VARCHAR(4),
  Trans_TellerId       VARCHAR(50),
  Trans_PayAcctNo      VARCHAR(50),
  Trans_RcvAcctNo      VARCHAR(50),
  Trans_Amt            DECIMAL(20,2),
  Trans_Currency       VARCHAR(10),
  Trans_DCFlag         VARCHAR(10),
  Trans_Status         VARCHAR(2),
  Trans_CheckStatus    VARCHAR(2),
  Trans_DepartmentId   VARCHAR(20),
   PRIMARY KEY (trans_hostseqno,trans_id)
  );
  
  create table ht_check_error(
  trans_hostseqno      VARCHAR(50) not null,
  trans_hostdate       DATE,
  trans_seqno          VARCHAR(50),
  trans_date           DATE,
  Trans_BusinessNo     VARCHAR(50),
  Trans_BusDeptId      VARCHAR(50),
  Trans_AcctDeptId     VARCHAR(50),
  Trans_Id             VARCHAR(4),
  Trans_TellerId       VARCHAR(50),
  Trans_PayAcctNo      VARCHAR(50),
  Trans_RcvAcctNo      VARCHAR(50),
  Trans_Amt            DECIMAL(20,2),
  Trans_Currency       VARCHAR(10),
  Trans_DCFlag         VARCHAR(10),
  Trans_Status         VARCHAR(2),
  Trans_CheckStatus    VARCHAR(2),
  Trans_DepartmentId   VARCHAR(20),
   PRIMARY KEY (trans_hostseqno,trans_id)
  );
  
  CREATE table fsp_verifycode(
 user_phone varchar(20),
 verifycode varchar(10),
 create_time datetime,
 PRIMARY KEY (user_phone)
);
  
 